ropensci/osmdata

R/getbb.R

I think that the repeated errors described in #192 were introduced by the new httr repeated query introduced in commit 86185db1ab1d0bf2875fe73e18161eca4c959fa7
My bounding box query now works straight away.

use already built query; might close issue #192

---

vignettes/osmdata.Rmd

Hi! I update the examples in the vignette according to your explanation in #186. 
In particular, when you define `dat <- c (53777, 238, 908, 1, 49)` I think you should set the number of multilinestrings equal to 1 instead of 0 and exclude the multilinestring output just from `dat1`, i.e. `dat1 <- dat1 [c (1:3, 5)]` instead of `dat <- dat [c (1:3, 5)]`. 
The other change is used to automatically update the description of the examples using R code instead of fixed numeric input. I'm not sure if it works on the online vignette or if you like that so I changed that only in two places but I could provide more commits if you thinks it's a good idea.

Update AND and OR examples

---

NEWS.md

I noticed that CRAN does not [render the NEWS](https://cran.r-project.org/web/packages/osmdata/news/news.html) very well:
Presumably CRAN does not treat NEWS.md as CommonMark but some other (pandoc?) markdown variant. I added some blank lines so that CRAN will render the lists nicely. (cf. {httr}'s NEWS.md on [CRAN](https://cran.r-project.org/web/packages/httr/news/news.html) and [GitHub](https://github.com/r-lib/httr/blob/master/NEWS.md) -> httr 1.4.0)
NB The current NEWS.md is valid CommonMark (at least with respect to the lists): 
> no blank line is needed to separate a paragraph from a following list ([Example 273](https://spec.commonmark.org/0.29/#example-273))
It is just that CRAN does not treat it as such (for reasons unknown to me). `utils::news(package = "osmdata")` OTOH renders …

add blank lines to NEWS.md

---

README.Rmd
README.md

We can't assume that every user of R `osmdata` will have realised that OSM's data has a particular licence, with implications for how they may re-use it. It is responsible to add a brief note about this.

Add note about OSM's licence

---

R/utils.R

changes the conversion of subgeometries to from st_polygon to st_multipolygon in the unname_osm helper function. Fixes bug here: https://github.com/ropensci/osmdata/issues/219

fixes #219

---

R/features.R

Fixes #211 by extracting from `href` rather than `title`.
Title entries in fact contain spaces in lieu of underscores.
Fixes #207

Fix available_features and available_tags

---

R/utils.R

I was reading the documentation for `unname_osmdata_sf` and spotted a small issue with documentation, i.e. missing initial \` when refering to `osmdata`

fix code style for unname_osmdata_sf

---

R/osmdata-methods.R
tests/testthat/test-osmdata.R

Fixes #235, updated the `print.osmdata` method to return x invisibly.
Added test for this expectation.

Fix print method to invisibly return x

---

DESCRIPTION
R/opq.R
codemeta.json
man/add_osm_feature.Rd
man/add_osm_features.Rd

Adds a documentation section to `add_osm_feature` and `add_osm_features` that briefly explains how the two functions differ.
closes #240

Document differences between `add_osm_feature` and `add_osm_features`

---

R/trim-osmdata.R
man/trim_osmdata.Rd

This is adding a warning Note to `trim_osmdata()` help page about possible problems with polygons downloaded from Nominatim.
Discussed previously in #253

Warning for trim_osmdata function

---

DESCRIPTION
vignettes/query-split.Rmd

Adding examples of bbox splitting for larger queries.
#254

Extending query split vignette

---

CONTRIBUTING.md

The link to Code of Conduct in Contributing.md seems to be dead; I believe the correct one lives in .github repository

re-animate a dead link to code of conduct

---

R/getbb.R
tests/testthat/test-getbb.R

- fix(getbb): add check for NA values w/ test
- fix(bbox_to_string): add check for NA values
Adding the check to bbox_to_string() alone didn't fix the issue since `getbb()` doesn't pass the results to `bbox_to_string()` if `format_out == "matrix"`. I used what I hope is a more informative error message for `getbb()`. The check for `bbox_to_string()` may be superfluous – `bbox_to_string(NA)` returns an error for non-numeric values – but I wanted to include it in this PR anyway since it was suggested as the approach.

fix(getbb): add check for NA values to close #280

---

DESCRIPTION
R/features.R
R/opq.R
man/add_osm_features.Rd
man/opq_osm_id.Rd
tests/testthat/test-opq.R
tests/testthat/test-osmdata.R
tests/testthat/test-set_bind_key_pre.R

This pull request updates `add_osm_features()` per #277. I was initially trying to support the option of passing a custom key_pre and bind vector along with the named vector or list of features. To do this I created a helper function, set_bind_key_pre() to share handling of key_exact and value_exact w/ `add_osm_feature()`. Ultimately, I decided a less granular approach that supported the same key_exact and value_exact parameters as `add_osm_feature()` was sufficient but left the structure in place if needed in the future for more customizable queries. I also added several other utility functions that I thought helped make the code more readable but can incorporate back into the main functions if preferred.
I also included a small bug fix for `available_tags()`. Currently, if there is a …

update `add_osm_features()` per #277 + minor bugfix for `available_tags()` + possible `opq_osm_id()` feature addition

---

R/opq.R
tests/testthat/test-opq.R

Fix https://github.com/ropensci/osmdata/issues/268
Examples on the documentation now works

Fix opq_osm_id for more than 1 id

---

R/opq.R
man/opq_osm_id.Rd
tests/testthat/test-opq.R

Requires https://github.com/ropensci/osmdata/pull/282

Allow vectors of ids + types for opq_osm_id

---

R/get-osmdata.R
R/opq.R
man/opq.Rd
man/osmdata_data_frame.Rd
tests/testthat/test-data_frame-osm.R
tests/testthat/test-opq.R

I can replicate the option for `opq_osm_id`, `opq_enclosing` and `opq_around`

Add the parameter `out` to `opq` to select the level of verbosity of the results

---

R/get-osmdata.R
tests/testthat/test-osmdata.R

Now the code match the documentation and works for calls with `doc` and no `q` parameter.
TODO: `osmdata_sc` fails because it requires the bbox

Fix the logic of parameter checks for osmdata_*(doc = doc)

---

R/get-osmdata.R
R/opq.R
man/opq.Rd
tests/testthat/test-data_frame-osm.R
tests/testthat/test-opq.R

Implement adiff queries in opq

---

R/get-osmdata.R
tests/testthat/test-data_frame-osm.R

Preallocate tag columns in a matrix and use xml2 to extract the values for all the nodes in one call for each column.
``` r
library(xml2)
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
q0 <- opq (bbox = c(-0.27, 51.47, -0.20, 51.50))
q1 <- add_osm_feature (q0, key = "name", value = "River Thames")
doc <- osmdata_xml (q1, filename = test_path ("export.osm"))
doc <- xml2::read_xml ( test_path ("export.osm"))
stringsAsFactors <- FALSE
osm_obj <- xml2::xml_find_all (doc, ".//node|.//way|.//relation")
mb <- list()
impl <- list()
impl$baseline <- function(osm_obj=osm_obj) {
tags <- xml2::xml_find_all (osm_obj, xpath = ".//tag", flatten = FALSE)
tagsL <- lapply (tags, function(x) {
tag <- xml2::xml_attrs (x)
tag <- structure (lapply …
```

Optimize osmdata data frame

---

DESCRIPTION
NEWS.md
R/get-osmdata.R
codemeta.json
tests/testthat/fixtures/osm-key_clashes.osm
tests/testthat/fixtures/osm-multi.osm
tests/testthat/test-data_frame-osm.R
tests/testthat/test-extract.R
tests/testthat/test-sc-osm.R
tests/testthat/test-sf-osm.R
tests/testthat/test-sp-osm.R

FIX #301 and handle cases with clashes between OSM keys and id or metadata columns

Fix key modifications for non-valid column names in osmdata_* functions

---

R/opq.R
man/opq.Rd

Deprecate nodes_only as per #308

---

NEWS.md
R/opq.R
tests/testthat/test-osmdata.R

The filter requires a ~ bind operator instead of =

Fix queries with !match_case and only one value

---

NEWS.md
R/opq.R
tests/testthat/test-opq.R

Example of the error for osm_types and features with non-multiple lengths
``` r
q <- opq("Catalunya") |> 
add_osm_features(features = c("\"amenity\"=\"school\"",
"\"amenity\"=\"kindergarten\"",
"\"amenity\"=\"music_school\"",
"\"amenity\"=\"language_school\"",
"\"amenity\"=\"dancing_school\""))
opq_string(q)
#> Error in sprintf("  %s %s (%s);\n", opq$osm_types, features, opq$bbox) :
#>  arguments cannot be recycled to the same length
```
For osm_types and features with multiple lengths, every feature gets only one osm_type instead of all osm_types
``` r
q <- opq("Catalunya") |> 
add_osm_features(features = c("\"amenity\"=\"school\"",
"\"amenity\"=\"kindergarten\"",
"\"amenity\"=\"music_school\""))
cat(opq_string(q))
#> [out:xml][timeout:25];
#> (
#>   node ["amenity"="school"] …
```

Fix queries with multiple features and more than one osm_types

---

_pkgdown.yml

to not lose the search bar with the new pgkdown version

docs: remove useless navbar config

---

DESCRIPTION
NEWS.md
README.Rmd
README.md
codemeta.json

@joostschouppe This adds a clear example early on in the README. Do you think that clarifies the issue?

describe key-only queries in readme; closes #342

---

DESCRIPTION
NEWS.md
R/get-osmdata-df.R
R/get-osmdata-sc.R
R/get-osmdata-sf.R
R/get-osmdata-sp.R
R/get-osmdata.R
R/getbb.R
codemeta.json

Set encoding to UTF-8 for tags and user names

---

DESCRIPTION
NEWS.md
R/elevation.R
R/get-osmdata-df.R
R/get-osmdata-sc.R
R/get-osmdata-sf.R
R/get-osmdata-sp.R
R/get-osmdata-xml.R
R/opq.R
R/osm-extract.R
R/poly2line.R
R/trim-osmdata.R
R/unique-osmdata.R
R/utils.R
codemeta.json
man/add_osm_feature.Rd
man/opq_csv.Rd
man/osm_elevation.Rd
man/osm_multipolygons.Rd
man/osm_poly2line.Rd
man/osm_polygons.Rd
man/osmdata_data_frame.Rd
man/osmdata_sc.Rd
man/osmdata_sf.Rd
man/osmdata_sp.Rd
man/osmdata_xml.Rd
man/trim_osmdata.Rd
man/unique_osmdata.Rd
man/unname_osmdata_sf.Rd

Simplify examples assuming R >= 4.1 + fixes from examplesIf branch
FIX #358
DROP #369

Depend on R >= 4.1 after dropping magrittr dependence

---

DESCRIPTION
NEWS.md
R/get-osmdata-df.R
man/osmdata_data_frame.Rd

Consistent among other `osmdata_*()` functions. See #374

Add `osmadata_data.frame` class to the results from `osmdata_data_frame()`

---

R/getbb.R

@jmaspons Without this it fails on, for example, `getbb("london uk", format_out = "polygon")`. That's because of these lines:
https://github.com/ropensci/osmdata/blob/d926e6faca57d0ad9ff5cb9686bcc3d8e0c740ba/R/getbb.R#L310-L311,
which sub-set `ret_poly$geometry`. In that case `order_poly` is 2:1, and the sub-setting removes all attributes when `sf` is not loaded. (`sf` has it's own sub-setting generic, so all works if and only if that namespace is loaded.) This then leads to this:
https://github.com/ropensci/osmdata/blob/d926e6faca57d0ad9ff5cb9686bcc3d8e0c740ba/R/get-osmdata-sf.R#L139-L142,
but those attributes have been removed by the sub-setting, and so `sf_column` is `integer(0)`, and `make_sf()` fails from that point on.

replace attributes in getbb sf_polygon for #377
